[package]
name = "ezk-srtp"
version = "0.2.0"
description = "Pure Rust SRTP/SRTCP implementation"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes = "0.9"
aes-gcm = "0.11"
ctr = "0.10"
hmac = "0.13"
log = "0.4"
sha1 = "0.11"
subtle = "2"
thiserror = "2"
zeroize = "1"

[dev-dependencies]
libsrtp = { workspace = true }
rand = "0.10"

[lints]
workspace = true
